export const coursesData = [
  {
    id: "MA5.101",
    name: "Discrete Structures",
    type: "common",
    selected: false,
  },
  {
    id: "CS0.101",
    name: "Computer Programming",
    type: "common",
    selected: false,
  },
  {
    id: "EC2.101",
    name: "Digital Systems and Microcontrollers",
    type: "common",
    selected: false,
  },
  {
    id: "MA4.101",
    name: "Real Analysis",
    type: "common",
    selected: false,
  },
  {
    id: "OC2.101",
    name: "Arts-1",
    type: "common",
    selected: false,
  },
  {
    id: "OC3.101",
    name: "Value Education-1",
    type: "common",
    selected: false,
  },
  {
    id: "OC1.101",
    name: "Sports-1",
    type: "common",
    selected: false,
  },
  {
    id: "EC5.101",
    name: "Networks Signals and Systems",
    type: "common",
    selected: false,
  },
  {
    id: "EC2.102",
    name: "Electronic Workshop-1 (H2)",
    type: "h2",
    selected: false,
  },
  {
    id: "SC4.101",
    name: "Computing in Sciences-1(H)",
    type: "common",
    selected: false,
  },
  {
    id: "CL1.101",
    name: "Introduction to Linguistics-1",
    type: "common",
    selected: false,
  },
  {
    id: "HS8.101",
    name: "Making of Contemporary World",
    type: "common",
    selected: false,
  },
  {
    id: "HS7.101",
    name: "Human Sciences Lab-1 (H2)",
    type: "h2",
    selected: false,
  },
  {
    id: "CS3.303",
    name: "Introduction to IoT",
    type: "common",
    selected: false,
  },
  {
    id: "CS1.301",
    name: "Algorithm Analysis and Design",
    type: "common",
    selected: false,
  },
  {
    id: "CS3.301",
    name: "Operating Systems and Networks",
    type: "common",
    selected: false,
  },
  {
    id: "CS4.301",
    name: "Data and Applications (H1)",
    type: "h1",
    selected: false,
  },
  {
    id: "CS1.302",
    name: "Automata Theory (H2)",
    type: "h2",
    selected: false,
  },
  {
    id: "SC1.110",
    name: "Science I",
    type: "common",
    selected: false,
  },
  {
    id: "SC1.421",
    name: "Introduction to Quantum Field Theory",
    type: "common",
    selected: false,
  },
  {
    id: "MA6.101",
    name: "Probability and Statistics",
    type: "common",
    selected: false,
  },
  {
    id: "EC2.103",
    name: "Analog Electronic Circuits",
    type: "common",
    selected: false,
  },
  {
    id: "EC2.201",
    name: "VLSI Design",
    type: "common",
    selected: false,
  },
  {
    id: "EC5.202",
    name: "Systems Thinking",
    type: "common",
    selected: false,
  },
  {
    id: "EC5.204",
    name: "Communication and Controls in IoT (H1)",
    type: "h1",
    selected: false,
  },
  {
    id: "EC5.201",
    name: "Signal Processing (not offering in M21)",
    type: "common",
    selected: false,
  },
  {
    id: "SC2.101",
    name: "General and Structural Chemistry",
    type: "common",
    selected: false,
  },
  {
    id: "SC1.203",
    name: "Quantum Mechanics",
    type: "common",
    selected: false,
  },
  {
    id: "SC3.101",
    name: "Introduction to Biology",
    type: "common",
    selected: false,
  },
  {
    id: "SC3.316",
    name: "Mathematical Models in Biology",
    type: "common",
    selected: false,
  },
  {
    id: "CL2.203",
    name: "Language and Society",
    type: "common",
    selected: false,
  },
  {
    id: "CL3.202",
    name: "Computational Linguistics II: Comp Semantics and Discourse parsing",
    type: "common",
    selected: false,
  },
  {
    id: "HS0.202",
    name: "Thinking and Knowing in the Human Sciences - II",
    type: "common",
    selected: false,
  },
  {
    id: "HS0.301",
    name: "Classical Text Readings - I",
    type: "common",
    selected: false,
  },
  {
    id: "EC3.202",
    name: "Embedded Systems Workshop",
    type: "common",
    selected: false,
  },
  {
    id: "SC2.304",
    name: "Spectroscopy(H1)",
    type: "h1",
    selected: false,
  },
  {
    id: "SC2.305",
    name: "Chemical Kinetics and Reaction Dynamics (H2)",
    type: "h2",
    selected: false,
  },
  {
    id: "SC3.202",
    name: "Bioinformatics (H1)",
    type: "h1",
    selected: false,
  },
  {
    id: "SC3.203",
    name: "Systems Biology (H2)",
    type: "h2",
    selected: false,
  },
  {
    id: "SC9.302",
    name: "CNS Honors - 1",
    type: "common",
    selected: false,
  },
  {
    id: "SC9.600",
    name: "CCNSB Seminar-3",
    type: "common",
    selected: false,
  },
  {
    id: "CS7.501",
    name: "Advanced NLP (100)",
    type: "common",
    selected: false,
  },
  {
    id: "CL9.302",
    name: "CL-Honours-1",
    type: "common",
    selected: false,
  },
  {
    id: "HS0.303",
    name: "Applied Ethics",
    type: "common",
    selected: false,
  },
  {
    id: "HS9.302",
    name: "HS-Honours-1",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.401",
    name: "BTP II / CSE-Honours Project III",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.402",
    name: "BTP II / CSE-Honours Project III",
    type: "common",
    selected: false,
  },
  {
    id: "HS0.203",
    name: "Basics of Ethics (H1)",
    type: "h1",
    selected: false,
  },
  {
    id: "EC9.402",
    name: "BTP II/ECE-Honours Project III",
    type: "common",
    selected: false,
  },
  {
    id: "EC9.401",
    name: "BTP II/ECE-Honours Project III",
    type: "common",
    selected: false,
  },
  {
    id: "SC9.402",
    name: "CNS-Honours Project III",
    type: "common",
    selected: false,
  },
  {
    id: "CL9.402",
    name: "CL-Honours Project III",
    type: "common",
    selected: false,
  },
  {
    id: "CNO",
    name: "CName",
    type: "common",
    selected: false,
  },
  {
    id: "CS1.304",
    name: "Data Structures & Algorithms for Problem Solving",
    type: "common",
    selected: false,
  },
  {
    id: "MA6.301",
    name: "Maths for Computer Science 1- Probability and Statistics (H1)",
    type: "h1",
    selected: false,
  },
  {
    id: "MA6.302",
    name: "Maths for Computer Science 2 - Linear Algebra (H2)",
    type: "h2",
    selected: false,
  },
  {
    id: "CS6.302",
    name: "Software Systems Development",
    type: "common",
    selected: false,
  },
  {
    id: "CS3.304",
    name: "Advanced Operating Systems",
    type: "common",
    selected: false,
  },
  {
    id: "Credits",
    name: "Faculty Name(s)",
    type: "common",
    selected: false,
  },
  {
    id: "3-1-0-4",
    name: "Anil Kumar V + Chiranjeevi Yarra",
    type: "common",
    selected: false,
  },
  {
    id: "CL5.401",
    name: "Topics in SSMT",
    type: "common",
    selected: false,
  },
  {
    id: "CS7.404",
    name: "Digital Image Processing",
    type: "common",
    selected: false,
  },
  {
    id: "EC5.408",
    name: "Speech Signal Processing",
    type: "common",
    selected: false,
  },
  {
    id: "CS7.403",
    name: "Statistical Methods in AI (200)",
    type: "common",
    selected: false,
  },
  {
    id: "EC5.407",
    name: "Wireless Communications",
    type: "common",
    selected: false,
  },
  {
    id: "EC5.409",
    name: "Radar Systems",
    type: "common",
    selected: false,
  },
  {
    id: "EC5.406",
    name: "Signal Detection and Estimation Theory",
    type: "common",
    selected: false,
  },
  {
    id: "EC2.401",
    name: "Analog IC Design",
    type: "common",
    selected: false,
  },
  {
    id: "EC2.407",
    name: "Design for Testability",
    type: "common",
    selected: false,
  },
  {
    id: "CS2.401",
    name: "FPGA based Accelerator Design",
    type: "common",
    selected: false,
  },
  {
    id: "EC2.406",
    name: "CMOS Radio Frequency Integrated Circuit Design",
    type: "common",
    selected: false,
  },
  {
    id: "CS7.503",
    name: "Mobile Robotics",
    type: "common",
    selected: false,
  },
  {
    id: "EC4.401",
    name: "Robotics: Dynamics and Control",
    type: "common",
    selected: false,
  },
  {
    id: "CS7.502",
    name: "Topics in Machine Learning Prerequisite: Statistical Methods in AI",
    type: "common",
    selected: false,
  },
  {
    id: "CE4.601",
    name: "Applied Regression Analysis",
    type: "common",
    selected: false,
  },
  {
    id: "CS4.408",
    name: "Spatial Informatics (50)",
    type: "common",
    selected: false,
  },
  {
    id: "CE0.501",
    name: "Theory of Elasticity and Plasticity",
    type: "common",
    selected: false,
  },
  {
    id: "CE1.607",
    name: "Earthquake Resistant Design of Masonry Structures",
    type: "common",
    selected: false,
  },
  {
    id: "CE1.604",
    name: "Advanced Structural Design",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.428",
    name: "Environmental Science & Technology (Open Elective)",
    type: "common",
    selected: false,
  },
  {
    id: "CE1.605",
    name: "IS Codes on Design and Structural Safety Assessment",
    type: "common",
    selected: false,
  },
  {
    id: "CE1.509",
    name: "Structural Wind Engineering",
    type: "common",
    selected: false,
  },
  {
    id: "CS1.405",
    name: "Modern Complexity Theory (100)",
    type: "common",
    selected: false,
  },
  {
    id: "CS1.402",
    name: "Principles of Programming Languages (100)",
    type: "common",
    selected: true,
  },
  {
    id: "CS3.401",
    name: "Distributed Systems (150)",
    type: "common",
    selected: false,
  },
  {
    id: "CS4.401",
    name: "Data Systems",
    type: "common",
    selected: true,
  },
  {
    id: "CS3.402",
    name: "Advanced Computer Networks (150)",
    type: "common",
    selected: false,
  },
  {
    id: "CS4.406",
    name: "Information Retrieval & Extraction (100)",
    type: "common",
    selected: false,
  },
  {
    id: "CS4.405",
    name: "Data Analytics I (100)",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.426",
    name: "Intro to Cognitive Science (50)",
    type: "common",
    selected: false,
  },
  {
    id: "CS3.502",
    name: "Real-Time Systems (50)",
    type: "common",
    selected: false,
  },
  {
    id: "CS8.501",
    name: "Research in Information Security",
    type: "common",
    selected: true,
  },
  {
    id: "CS4.404",
    name: "Advanced Data Systems",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.425",
    name: "Social Science Perspective on HCI (Open Elective) (Max:60 Students)",
    type: "common",
    selected: false,
  },
  {
    id: "CS3.403",
    name: "Distributing Trust and Block Chains (Max: 40 Students)",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.427",
    name: "Introduction to Neural and Cognitive Modeling",
    type: "common",
    selected: false,
  },
  {
    id: "HS3.201",
    name: "Introduction to History",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.421",
    name: "Behavioral Research & Experimental Design (30)",
    type: "common",
    selected: true,
  },
  {
    id: "CS9.424",
    name: "Technology Product Entrepreneurship (50)",
    type: "common",
    selected: false,
  },
  {
    id: "CE5.502",
    name: "Hydrological modelling and Software Development (40) (Open Elective)",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.313",
    name: "Eco-Informatics (Open Elective)",
    type: "common",
    selected: false,
  },
  {
    id: "CS6.501",
    name: "Topics in Software Engineering",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.423",
    name: "Introduction to Neuroeconomics (26)",
    type: "common",
    selected: false,
  },
  {
    id: "CS4.407",
    name: "Online Privacy",
    type: "common",
    selected: true,
  },
  {
    id: "CS7.504",
    name: "Fairness, Privacy and Ethics in AI",
    type: "common",
    selected: false,
  },
  {
    id: "CS3.306",
    name: "Algorithms and Operating Systems (Open Elective for UG ECE/D students only)",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.429",
    name: "Design for Social Innovation",
    type: "common",
    selected: false,
  },
];
