export const coursesData = [
  {
    id: "CS6.301",
    name: "Design and Analysis of Software Systems",
    type: "common",
    selected: true,
  },
  {
    id: "CS7.301",
    name: "Machine, Data and Learning",
    type: "common",
    selected: true,
  },
  {
    id: "HS8.102",
    name: "Intro to Human Sciences",
    type: "common",
    selected: true,
  },
  {
    // Manually added
    id: "HSS317",
    name: "Ethics",
    type: "common",
    selected: false,
  },
  {
    // Manually added
    id: "HS1.202",
    name: "Readings in Indian Literatures",
    type: "h2",
    selected: false,
  },
  {
    // Manually added
    id: "HS1.203",
    name: "Literature, History and Belonging in Hyderabad",
    type: "h2",
    selected: false,
  },
  {
    // Manually added
    id: "HSS337",
    name: "Comprehension of Indian Music",
    type: "common",
    selected: false,
  },
  {
    // Manually added
    id: "HS3.301",
    name: "Alternate Religious Traditions in Indian History",
    type: "common",
    selected: false,
  },
  {
    // Manually added
    id: "HSS318",
    name: "Introduction to Philosophy of Technology",
    type: "common",
    selected: false,
  },
  {
    // Manually added
    id: "HSS445",
    name: "Literature –American Classics",
    type: "common",
    selected: false,
  },
  {
    // Manually added
    id: "IMA409",
    name: "Multivariate Analysis",
    type: "common",
    selected: false,
  },
  {
    // Manually added
    id: "IMA303",
    name: "Differential Equations",
    type: "common",
    selected: false,
  },
  {
    // Manually added
    id: "MA4.302",
    name: "Linear Partial Differential Equations and Variational Calculus",
    type: "common",
    selected: false,
  },
  {
    id: "SC1.111",
    name: "Science II",
    type: "common",
    selected: false,
  },
  {
    id: "CS1.302",
    name: "Automata Theory",
    type: "h2",
    selected: true,
  },
  {
    id: "OC3.102",
    name: "Value Education II",
    type: "common",
    selected: true,
  },
  {
    id: "CS9.312",
    name: "Introduction to Quantum Information and Computation",
    type: "h2",
    selected: false,
  },
  {
    id: "EC5.205",
    name: "Introduction to Coding Theory",
    type: "h1",
    selected: true,
  },
  {
    id: "CS3.302",
    name: "Software Programming for Performance",
    type: "h2",
    selected: true,
  },
  {
    id: "CS7.303",
    name: "Digital Signal Analysis",
    type: "h2",
    selected: false,
  },
  {
    id: "CS9.301",
    name: "Introduction to Brain and Cognition",
    type: "h1",
    selected: false,
  },
  {
    id: "CS7.302",
    name: "Computer Graphics",
    type: "h2",
    selected: true,
  },
  {
    id: "EC5.203",
    name: "Communication Theory",
    type: "common",
    selected: false,
  },
  {
    id: "EC6.202",
    name: "Intro to Processor Architecture",
    type: "h1",
    selected: false,
  },
  {
    id: "EC2.201",
    name: "VLSI Design",
    type: "common",
    selected: false,
  },
  {
    id: "EC2.203",
    name: "Intro to Bio Electronics",
    type: "h2",
    selected: false,
  },
  {
    id: "CS2.201",
    name: "Computer System Organization",
    type: "common",
    selected: false,
  },
  {
    id: "SC1.204",
    name: "Thermodynamics",
    type: "h1",
    selected: false,
  },
  {
    id: "SC1.205",
    name: "Statistical Mechanics",
    type: "h2",
    selected: false,
  },
  {
    id: "SC2.203",
    name: "Biomolecular Structures",
    type: "h1",
    selected: false,
  },
  {
    id: "SC2.202",
    name: "Organic Chemistry",
    type: "h2",
    selected: false,
  },
  {
    id: "CL1.204",
    name: "Language Typology and Universals",
    type: "common",
    selected: false,
  },
  {
    id: "CS7.401",
    name: "Introduction to NLP",
    type: "common",
    selected: false,
  },
  {
    id: "HS0.302",
    name: "Research Methods in Human Sciences",
    type: "common",
    selected: false,
  },
  {
    id: "HS7.301",
    name: "Science, Technology and Society",
    type: "common",
    selected: false,
  },
  {
    id: "HS2.302",
    name: "Gender, Kinship, and State Law",
    type: "h2",
    selected: false,
  },
  {
    id: "CS3.305",
    name: "Computer Networks",
    type: "h1",
    selected: false,
  },
  {
    id: "CSE494",
    name: "Honours Project IV",
    type: "common",
    selected: false,
  },
  {
    id: "ECE494",
    name: "ECE-Honours Project IV",
    type: "common",
    selected: false,
  },
  {
    id: "SCI473",
    name: "CNS-Honours Project IV",
    type: "common",
    selected: false,
  },
  {
    id: "SCI400",
    name: "CCNSB Seminar",
    type: "common",
    selected: false,
  },
  {
    id: "CNO",
    name: "CName",
    type: "common",
    selected: false,
  },
  {
    id: "CSE538",
    name: "System and Network Security",
    type: "common",
    selected: false,
  },
  {
    id: "CSE418",
    name: "Principles of Information Security",
    type: "common",
    selected: false,
  },
  {
    id: "CSE704",
    name: "PG-Project (8 Cr)",
    type: "common",
    selected: false,
  },
  {
    id: "CSE581",
    name: "Information Security Audit and Assurance",
    type: "common",
    selected: false,
  },
  {
    id: "CS0.302",
    name: "Computing Tools",
    type: "common",
    selected: false,
  },
  {
    id: "SC3.303",
    name: "Advanced Bioinformatics",
    type: "common",
    selected: false,
  },
  {
    id: "SCI860",
    name: "Computational Biology Project / Elective",
    type: "common",
    selected: false,
  },
  {
    // Manually added
    id: "SC2.316",
    name: "Molecular Modeling and Simulations",
    type: "common",
    selected: false,
  },
  {
    id: "SCI761",
    name: "Topics in Nanosciences",
    type: "common",
    selected: false,
  },
  {
    id: "SC1.315",
    name: "Nonlinear Dynamics",
    type: "common",
    selected: false,
  },
  {
    id: "SC1.320",
    name: "Introduction to Particle Physics",
    type: "common",
    selected: false,
  },
  {
    id: "SCI477",
    name: "Machine Learning for Natural Sciences",
    type: "common",
    selected: false,
  },
  {
    id: "SC2.301",
    name: "Physics of Soft Condensed Matter",
    type: "common",
    selected: false,
  },
  {
    id: "CLG452",
    name: "Linguistic Data 2: Collection & Modeling",
    type: "common",
    selected: false,
  },
  {
    id: "CS4.501",
    name: "Social Computing",
    type: "common",
    selected: false,
  },
  {
    id: "ECE442",
    name: "Time Frequency Analysis",
    type: "common",
    selected: false,
  },
  {
    id: "ECE431",
    name: "Signal Detection and Estimation Theory",
    type: "common",
    selected: false,
  },
  {
    id: "EC5.405",
    name: "Medical Image Analysis",
    type: "common",
    selected: false,
  },
  {
    id: "CSE578",
    name: "Computer Vision",
    type: "common",
    selected: false,
  },
  {
    id: "CSE471",
    name: "Statistical Methods in AI",
    type: "common",
    selected: false,
  },
  {
    id: "EC2.405",
    name: "Applied Electromagnetics",
    type: "common",
    selected: false,
  },
  {
    id: "ECE537",
    name: "Topics in Coding Theory",
    type: "common",
    selected: false,
  },
  {
    id: "EC2.404",
    name: "Design Verification and System Verilog",
    type: "common",
    selected: false,
  },
  {
    id: "ECE463",
    name: "Digital VLSI Design",
    type: "common",
    selected: false,
  },
  {
    id: "ECE562",
    name: "Flexible Electronics",
    type: "common",
    selected: false,
  },
  {
    id: "EC4.403",
    name: "Robotics: Planning and Navigation",
    type: "common",
    selected: false,
  },
  {
    id: "EC4.402",
    name: "Intro to UAV Design",
    type: "common",
    selected: false,
  },
  {
    id: "ECE551",
    name: "Advances in Robotics & Control",
    type: "common",
    selected: false,
  },
  {
    id: "CES442",
    name: "Disaster Management (40)",
    type: "common",
    selected: false,
  },
  {
    id: "CE1.603",
    name: "Advanced Structural Analysis",
    type: "common",
    selected: false,
  },
  {
    id: "CEW612",
    name: "Design of Hydraulic Structures",
    type: "common",
    selected: false,
  },
  {
    id: "CES617",
    name: "Stability of Structures",
    type: "common",
    selected: false,
  },
  {
    id: "CES641",
    name: "Earthquake Engineering",
    type: "common",
    selected: false,
  },
  {
    id: "CEG461",
    name: "Remote Sensing (40)",
    type: "common",
    selected: false,
  },
  {
    id: "CEG422",
    name: "Green Buildings (40)",
    type: "common",
    selected: false,
  },
  {
    id: "CES771",
    name: "CASE Project",
    type: "common",
    selected: false,
  },
  {
    id: "CSE481",
    name: "Optimization Methods",
    type: "common",
    selected: false,
  },
  {
    id: "CS1.406",
    name: "Adv. Algorithms",
    type: "common",
    selected: false,
  },
  {
    id: "CS4.401",
    name: "Data Systems",
    type: "common",
    selected: false,
  },
  {
    id: "CSE461",
    name: "Software Engineering",
    type: "common",
    selected: false,
  },
  {
    id: "CSE431",
    name: "Distributed Systems",
    type: "common",
    selected: false,
  },
  {
    id: "CSE595",
    name: "ICTs for Development",
    type: "common",
    selected: false,
  },
  {
    id: "CSE498",
    name: "Introduction to Game Theory",
    type: "common",
    selected: true,
  },
  {
    id: "CSE563",
    name: "Internals of Application Servers",
    type: "common",
    selected: false,
  },
  {
    id: "CSE586",
    name: "Cognitive Neuroscience",
    type: "common",
    selected: false,
  },
  {
    id: "CSE588",
    name: "Music, Mind, and Technology",
    type: "common",
    selected: false,
  },
  {
    id: "CSE567",
    name: "Usability Engineering",
    type: "common",
    selected: false,
  },
  {
    id: "CS7.601",
    name: "Deep Learning: Theory and Practices",
    type: "common",
    selected: false,
  },
  {
    id: "CS4.403",
    name: "Distributed Data Systems",
    type: "common",
    selected: false,
  },
  {
    id: "CS1.501",
    name: "Advanced Optimization: Theory and Applications",
    type: "common",
    selected: false,
  },
  {
    id: "CS9.422",
    name: "Behavioral Research: Statistical Methods",
    type: "h2",
    selected: false,
  },
  {
    id: "CEG462",
    name: "Hydro Informatics",
    type: "common",
    selected: false,
  },
];
